-- Execute este arquivo uma vez no SQL Editor do seu projeto Supabase.

create table if not exists public.user_data (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text not null default '',
  playlists_json jsonb not null default '{}'::jsonb,
  is_public boolean not null default false,
  friends uuid[] not null default '{}'::uuid[]
);

create table if not exists public.listening_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  track_name text not null default '',
  artist text not null default '',
  album_image_url text not null default '',
  media_id text not null default '',
  audio_url text not null default '',
  source_url text not null default '',
  license_name text not null default '',
  license_url text not null default '',
  listened_at timestamptz not null default now()
);

create table if not exists public.now_playing (
  user_id uuid primary key references auth.users(id) on delete cascade,
  track_name text not null default '',
  artist text not null default '',
  album_image_url text not null default '',
  media_id text not null default '',
  audio_url text not null default '',
  source_url text not null default '',
  license_name text not null default '',
  license_url text not null default '',
  updated_at timestamptz not null default now()
);

-- Permite reaplicar o schema em projetos de demonstração já existentes.
alter table public.listening_history add column if not exists media_id text not null default '';
alter table public.listening_history add column if not exists audio_url text not null default '';
alter table public.listening_history add column if not exists source_url text not null default '';
alter table public.listening_history add column if not exists license_name text not null default '';
alter table public.listening_history add column if not exists license_url text not null default '';
alter table public.now_playing add column if not exists media_id text not null default '';
alter table public.now_playing add column if not exists audio_url text not null default '';
alter table public.now_playing add column if not exists source_url text not null default '';
alter table public.now_playing add column if not exists license_name text not null default '';
alter table public.now_playing add column if not exists license_url text not null default '';

alter table public.user_data enable row level security;
alter table public.listening_history enable row level security;
alter table public.now_playing enable row level security;

drop policy if exists "user_data_own_select" on public.user_data;
create policy "user_data_own_select" on public.user_data for select to authenticated
  using (user_id = auth.uid());
drop policy if exists "user_data_own_insert" on public.user_data;
create policy "user_data_own_insert" on public.user_data for insert to authenticated
  with check (user_id = auth.uid());
drop policy if exists "user_data_own_update" on public.user_data;
create policy "user_data_own_update" on public.user_data for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "history_own_all" on public.listening_history;
create policy "history_own_all" on public.listening_history for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "now_playing_read" on public.now_playing;
create policy "now_playing_read" on public.now_playing for select to authenticated using (true);
drop policy if exists "now_playing_own_insert" on public.now_playing;
create policy "now_playing_own_insert" on public.now_playing for insert to authenticated
  with check (user_id = auth.uid());
drop policy if exists "now_playing_own_update" on public.now_playing;
create policy "now_playing_own_update" on public.now_playing for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

create or replace function public.search_users(query_text text)
returns table(user_id uuid, username text)
language sql stable security definer set search_path = public
as $$
  select u.user_id, u.username from public.user_data u
  where u.user_id <> auth.uid() and u.username ilike '%' || query_text || '%'
  order by u.username limit 30;
$$;

create or replace function public.get_friends_list(friend_ids uuid[])
returns table(user_id uuid, username text)
language sql stable security definer set search_path = public
as $$
  select u.user_id, u.username from public.user_data u
  where u.user_id = any(friend_ids) order by u.username;
$$;

create or replace function public.get_friend_profile(friend_uid uuid)
returns jsonb
language sql stable security definer set search_path = public
as $$
  select jsonb_build_object(
    'user_id', u.user_id,
    'username', u.username,
    'is_public', u.is_public,
    'playlists_json', case when u.is_public then u.playlists_json else '{}'::jsonb end
  ) from public.user_data u where u.user_id = friend_uid;
$$;

create or replace function public.get_top_artists(uid uuid, lim integer default 20)
returns table(artist text, play_count bigint)
language sql stable security invoker set search_path = public
as $$
  select h.artist, count(*) from public.listening_history h
  where h.user_id = auth.uid() and h.user_id = uid and h.artist <> ''
  group by h.artist order by count(*) desc limit greatest(0, lim);
$$;

drop function if exists public.get_top_tracks(uuid, integer);
create function public.get_top_tracks(uid uuid, lim integer default 50)
returns table(track_name text, artist text, album_image_url text, media_id text, play_count bigint)
language sql stable security invoker set search_path = public
as $$
  select h.track_name, h.artist, max(h.album_image_url), h.media_id, count(*)
  from public.listening_history h
  where h.user_id = auth.uid() and h.user_id = uid
  group by h.track_name, h.artist, h.media_id order by count(*) desc limit greatest(0, lim);
$$;

grant execute on function public.search_users(text) to authenticated;
grant execute on function public.get_friends_list(uuid[]) to authenticated;
grant execute on function public.get_friend_profile(uuid) to authenticated;
grant execute on function public.get_top_artists(uuid, integer) to authenticated;
grant execute on function public.get_top_tracks(uuid, integer) to authenticated;

